#! /usr/bin/env bash
# Check for bucket name
if [ -z "$1" ]; then
    echo "No bucket name provided eg. ./bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1

OBJECTS_TO_DELETE=$(aws s3api list-objects-v2 --bucket $BUCKET_NAME --query "{Objects: Contents[].{Key: Key}}" --output json)

aws s3api delete-objects \
--bucket $BUCKET_NAME \
--delete "$OBJECTS_TO_DELETE"

aws s3api delete-bucket \
--bucket $BUCKET_NAME