#! /usr/bin/env bash

set -e

# Check for bucket name
if [ -z "$1" ]; then
    echo "No bucket name provided eg. ./bucket my-bucket-name"
    exit 1
fi
# Check for prefix
if [ -z "$2" ]; then
    echo "No prefix provided"
    exit 1
fi

BUCKET_NAME=$1
FILENAME_PREFIX=$2


#where we store the files
OUTPUT_DIR="/tmp/s3-bash-scripts"

#Remove folder if it exists already to clear it
rm -r $OUTPUT_DIR

#Output folder
mkdir -p $OUTPUT_DIR
 

#Figure out how many files to create
NUM_FILES=$((RANDOM % 6 + 5))

for ((i-1;i<=$NUM_FILES; i++)); do  
    FILENAME="$OUTPUT_DIR/${FILENAME_PREFIX}_$i.txt"

    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM %1024 + 1)) 2>/dev/null
done

tree $OUTPUT_DIR

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files